replicaCount: 2

image:
  repository: 562437414591.dkr.ecr.eu-west-2.amazonaws.com/python-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

redis:
  image: redis:7
  port: 6379
  
externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager
  targetSecretName: redis-secret
  remoteSecretName: redis-app/dev/redis
  remoteSecretProperty: REDIS_PASSWORD

ingress:
  enabled: true
  host: localhost
  path: /api
  type: alb

canary:
  enabled: false
  tag: ""
  stableWeight: 100
  canaryWeight: 0