replicaCount: 2

image:
  repository: 562437414591.dkr.ecr.eu-west-2.amazonaws.com/python-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

redis:
  image: redis:7
  port: 6379
  password: redis-123

ingress:
  enabled: true
  host: localhost
  path: /api/?(.*)