image:
  repository: 562437414591.dkr.ecr.eu-west-2.amazonaws.com/python-api
  tag: "55"
  

externalSecret:
  enabled: true 
  refreshInterval: 1h 
  secretStoreName: aws-secrets-manager 
  targetSecretName: redis-secret 
  remoteSecretName: redis-app/dev/redis 
  remoteSecretProperty: REDIS_PASSWORD

ingress:
  enabled: true
  type: alb
  host: ""
  path: /api

canary:
  enabled: false
  tag: ""
  stableWeight: 100
  canaryWeight: 0