image:
  repository: 562437414591.dkr.ecr.eu-west-2.amazonaws.com/python-api
  tag: "latest"

ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip