{{- if .Values.canary.enabled}}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: python-api-canary
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
      version: canary 

  template:
    metadata:
      labels:
        app: python-api 
        version: canary 
    spec:
      containers:
        - name: python-api 
          image: "{{ .Values.image.repository }}:{{ .Values.canary.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: redis-cm
            - secretRef:
                name: redis-secret

{{- end }}