{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: redis-secret 
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore 

  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner 

  data:
    - secretKey: REDIS_PASSWORD 
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: {{ .Values.externalSecret.remoteSecretProperty }}

{{- end }} 